name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ubuntu-version: focal
            gr-version: 3.9.2
          - ubuntu-version: bionic
            gr-version: 3.8.2
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMG: ${{ secrets.DOCKERHUB_USERNAME }}/gnuradio-oot-dev
        with:
          push: true
          build-args: |
            dist=ubuntu:${{ matrix.ubuntu-version }}
            gr_version=${{ matrix.gr-version }}
          tags: ${{ env.IMG }}:${{ matrix.gr-version }}-${{ matrix.ubuntu-version }}