name: OOT Dev Image - Manual Docker Hub Push
on:
  workflow_dispatch:
    inputs:
      distro:
        description: 'Linux Distribution'
        required: true
        default: 'ubuntu'
      distro_version:
        description: 'Distribution Version'
        required: true
        default: 'focal'
      gr_version:
        description: 'GR Version'
        required: true
        default: 3.10.1

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        env:
          IMG: ${{ secrets.DOCKERHUB_USERNAME }}/gnuradio-oot-dev
          TAG: ${{ github.event.inputs.gr_version }}-${{ github.event.inputs.distro }}-${{ github.event.inputs.distro_version }}
        with:
          push: true
          file: docker/oot-dev.dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          build-args: |
            dist=${{ github.event.inputs.distro }}:${{ github.event.inputs.distro_version }}
            gr_version=${{ github.event.inputs.gr_version }}
          tags: ${{ env.IMG }}:${{ env.TAG }}
          cache-from: type=registry,ref=${{ env.IMG }}:${{ env.TAG }}
          cache-to: type=inline